language: java
sudo: false
install: true
jdk: oraclejdk8
script: ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/jvm

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/com/github/drautureau-sonarsource
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false
  webhooks:
    - secure: "TODO"
  on_success: always
  on_failure: never
  on_start: never
  on_cancel: never
  on_error: never
